routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EtatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CsvExportController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);
Route::middleware(['auth'])->group(function () {
    

    Route::resource("categories",CategorieController::class);
    Route::resource("produits",ProduitController::class);
    Route::post('/logout', [LoginController::class,'logout'])->name('logout');
    Route::get('/register', [RegisterController::class,'showRegistrationForm']);
    Route::post('/register', [RegisterController::class,'register'])->name('register');
    Route::post('/commandes/{id}/etat',[EtatController::class,'changeEtat'])->name('etat.change');
    Route::get('/export-csv', [CsvExportController::class, 'export'])->name('exportcsv');
    
});

Route::get('/login',[LoginController::class,'showLoginForm']);
Route::post('/login', [LoginController::class,'login'])->name('login');

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    use HasFactory;
    protected $fillable=['nom','prenom','tele'];

    public function commandes(){
        return $this->hasMany(Commande::class);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;
use App\Models\Client;

use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $v=$request->validate([
            'nom'=>'required',
            'prenom'=>'required',
            'tele'=>'required'
            
        ]);
        $client=Client::create($v);
        return redirect()->route('commande.store_client',['id'=>$client->id]);

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/clients/create.blade.php
@extends('layouts.admin')
 @section('title','Enregistrer infos client')
 @section('content')
    <h1>Vos informations </h1>
    <form action="{{route('commandes.store')}}" method="POST">
        @csrf
        <div>
        <label for="nom">Nom</label>
        <input type="text" name="nom" id="nom" value="{{old('nom')}}">
        </div>
        <div>
        <label for="prenom">Prenom</label>
        <input type="text" name="prenom" id="prenom" value="{{old('prenom')}}">
        </div>
        <div>
        <label for="tele">Tele</label>
        <input type="text" name="tele" id="tele" value="{{old('tele')}}">
        </div>
         
        <div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/clients/created.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>created</p>
</body>
</html>