routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EtatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CsvExportController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);
Route::middleware(['auth'])->group(function () {
    

    Route::resource("categories",CategorieController::class);
    Route::resource("produits",ProduitController::class);
    Route::post('/logout', [LoginController::class,'logout'])->name('logout');
    Route::get('/register', [RegisterController::class,'showRegistrationForm']);
    Route::post('/register', [RegisterController::class,'register'])->name('register');
    Route::post('/commandes/{id}/etat',[EtatController::class,'changeEtat'])->name('etat.change');
    Route::get('/export-csv', [CsvExportController::class, 'export'])->name('exportcsv');
    
});

Route::get('/login',[LoginController::class,'showLoginForm']);
Route::post('/login', [LoginController::class,'login'])->name('login');

resources/views/categories/create.blade.php
 @extends('layouts.admin')
 @section('title','Ajouter une categorie')
 @section('content')
    <h1>Creer une nouvelle categorie</h1>
    <form action="{{route('categories.store')}}" method="POST">
        @csrf
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation')}}">
        </div>
         <div>
        <label for="description">Description</label>
       <textarea name="description" id="description" cols="30" rows="10" >{{old('designation')}}</textarea>
          
        </div>
        <div>
            <input type="submit" value="Ajouter">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/categories/edit.blade.php
 @extends('layouts.admin')
 @section('title','Modifier une categorie')
 @section('content')
    <h1>Modifier la categorie num {{$cat->id}}</h1>
    <form action="{{route('categories.update',["category"=>$cat->id])}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="designation">Designation</label>
        <input type="text" name="designation" id="designation" value="{{old('designation',$cat->designation)}}">
        </div>
         <div>
        <label for="description">Description</label>
       <textarea name="description" id="description" cols="30" rows="10" >{{old('designation',$cat->description)}}</textarea>
          
        </div>
        <div>
            <input type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>

@endsection

resources/views/categories/index.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des categories')
 @section('content')
     
    <h1>Liste des categories</h1>
    <a class="btn btn-primary "href="{{route('categories.create')}}">Ajouter une nouvelle categorie</a>
    <table class="table table-stripped" id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>Description</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($categories as $cat)
          <tr>
            <td>{{$cat->id}}</td>
            <td>{{$cat->designation}}</td>
            <td>{{$cat->description}}</td>
            <td><a href="{{route('categories.show',["category"=>$cat->id])}}">Details</a></td>
            <td><a href="{{route('categories.edit',["category"=>$cat->id])}}">Modifier</a></td>
            <td>
                <form action="{{route('categories.destroy',["category"=>$cat->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer cette categorie?')">
                </form></td>
          </tr>
      @endforeach
    </table>
 @endsection

resources/views/categories/show.blade.php
 @extends('layouts.admin')
 @section('title','Detail d \'une categorie')
 @section('content')
    <a href="{{route('categories.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie Num {{$cat->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$cat->designation}}</p>
        <p><strong>Description:</strong> {{$cat->description}}</p>
    </div>
@endsection