routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EtatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CsvExportController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);
Route::middleware(['auth'])->group(function () {
    

    Route::resource("categories",CategorieController::class);
    Route::resource("produits",ProduitController::class);
    Route::post('/logout', [LoginController::class,'logout'])->name('logout');
    Route::get('/register', [RegisterController::class,'showRegistrationForm']);
    Route::post('/register', [RegisterController::class,'register'])->name('register');
    Route::post('/commandes/{id}/etat',[EtatController::class,'changeEtat'])->name('etat.change');
    Route::get('/export-csv', [CsvExportController::class, 'export'])->name('exportcsv');
    
});

Route::get('/login',[LoginController::class,'showLoginForm']);
Route::post('/login', [LoginController::class,'login'])->name('login');

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>@yield('title','App store')</title>
</head>
<body>
    <div class="wrapper">
    <div class='d-flex justify-content-between'>
    <nav class="navbar navbar-expand-sm">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{route('home.index')}}">Catalogue</a></li>
            <li class="nav-item"><a class="nav-link " href="{{route('categories.index')}}">Gestion des categories</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('produits.index')}}">Gestion des produits</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('home.panier')}}">Mon panier</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('commandes.index')}}">Commandes</a></li>
        </ul>
    </nav>
    @auth
    <div >
    <form method="POST" action="{{ route('logout') }}">
        @csrf
        <input type="submit" class="btn btn-primary" value="Logout"></button>
    </form>
    @endauth
</div>
</div>
    <div class="main">
        @yield('content')
    </div>
</div>
    <footer class="footer">
        &copy;OFPPT 2024
    </footer>
</body>
</html>

resources/views/layouts/client.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>@yield('title','App store')</title>
</head>
<body>
    <div class="wrapper">
    <nav class="navbar navbar-expand-sm">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{route('home.index')}}">Catalogue</a></li>
            <li class="nav-item"><a class="nav-link" href="{{route('home.panier')}}">Mon panier</a></li>
        </ul>
    </nav>
    <div class="main">
        @yield('content')
    </div>
</div>
    <footer>
        &copy;OFPPT 2024
    </footer>
</body>
</html>