routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EtatController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProduitController;
use App\Http\Controllers\CommandeController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CsvExportController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/',[HomeController::class,"index"])->name('home.index');
Route::get('/panier',[HomeController::class,"show_panier"])->name('home.panier');
Route::get('/panier/clear',[HomeController::class,"clear"])->name('home.clear');
Route::post('panier/add/{id}',[HomeController::class,"add"])->name('home.add');
Route::delete('panier/delete/{id}',[HomeController::class,"delete"])->name('home.delete');
Route::resource("clients",ClientController::class);
Route::resource("commandes",CommandeController::class);
Route::middleware(['auth'])->group(function () {
    

    Route::resource("categories",CategorieController::class);
    Route::resource("produits",ProduitController::class);
    Route::post('/logout', [LoginController::class,'logout'])->name('logout');
    Route::get('/register', [RegisterController::class,'showRegistrationForm']);
    Route::post('/register', [RegisterController::class,'register'])->name('register');
    Route::post('/commandes/{id}/etat',[EtatController::class,'changeEtat'])->name('etat.change');
    Route::get('/export-csv', [CsvExportController::class, 'export'])->name('exportcsv');
    
});

Route::get('/login',[LoginController::class,'showLoginForm']);
Route::post('/login', [LoginController::class,'login'])->name('login');

app/Models/Produit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produit extends Model
{
    use HasFactory;
    protected $fillable=['designation','prix_u','quantite_stock','categorie_id','image'];
    public function categorie(){
        return  $this->belongsTo(Categorie::class);
     }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produit;
use App\Models\Categorie;
use Illuminate\Http\Request;

class ProduitController extends Controller
{
    //
        /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {

        $categories = Categorie::all();
        $des=$request->query("designation");
        $max=$request->query("max");
        $min=$request->query("min");
        $cate = $request->query('cate');
        $quantite_stock=$request->query("quantite_stock");
        if($des){
            $q=Produit::where('designation','like',"%".$des."%");
        }
        elseif ($max){
            $q=Produit::where('prix_u','<=',$max);
        }else if ($min) {
            $q=Produit::where('prix_u','>=',$min);
        }
        else if ($quantite_stock) {
            $q=Produit::where("quantite_stock","like","%".$quantite_stock."%");
        } 
        else if($cate){
            $q=Produit::where('categorie_id','like',$cate);
        }
        else {
            $q=Produit::query();
        }
        $produits=$q->paginate(10);
        return view("produits.index",compact("produits","categories"));
    }
    
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    { 
        $categories=Categorie::all();
        return view('produits.create',compact("categories"));
        
        
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // $cat=new Categorie();
        // $cat->designation=$request->input('designation');
        // $cat->description=$request->input('description');
        // $cat->save();
        $validateData = $request->validate([
            'designation'=>'required|unique:produits,designation',
            'prix_u'=>'required',
            'quantite_stock'=>'required',
            'categorie_id'=>'required',
            "image"=>"image|mimes:jpeg,png,jpg,gif,svg"
        ]);
        $imagePath = $request->file("image")->store("products/image","public");
        $validateData["image"] = $imagePath;
        Produit::create($validateData);
        return  redirect()->route('produits.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(int $id)
    {
        $prod=Produit::find($id);
        
        
        return view('produits.show')->with("prod",$prod);
    }

    /**
     * Show the form for editing the specified resource.
     */ 
    public function edit(string $id)
    {
        $prod=Produit::find($id);
        $categories = Categorie::all();
        return view('produits.edit',compact('prod',"categories"));
        }

    

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
          $validateData = $request->validate([
            'designation'=>'required|unique:produits,designation,'.$id,
            'prix'=>'required',
            'quantite_stock'=>'required',
            "image"=>"image|mimes:jpeg,png,jpg,gif,svg"
        ]);
        if($request->hasFile("image")) {
            $imagePath = $request->file("image")->store("products/image","public");
            $validateData["image"] = $imagePath;
        }
        $prod=Produit::find($id);
        $prod->update($validateData);
        return redirect()->route('produits.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        Produit::destroy($id);
        return  redirect()->route('produits.index');

    }


}

resources/views/produits/create.blade.php
 @extends('layouts.admin')
 @section('title','Ajouter un produit')
 @section('content')
 <div class="contain">
    <h1>Creer un nouveau produit </h1>
    <form action="{{route('produits.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
        <label for="designation">Designation :</label>
        <input type="text" name="designation" id="designation" value="{{old('designation')}}">
        </div>
        <br>
        <div class="form-group">
            <label for="prix_u">prix :</label>
            <input type="number" name="prix_u" id="prix_u" value="{{old('prix_u')}}">
        </div>        
        <br>
        <div class="form-group">
            <input type="file" name="image" id="image" accept="images/*">
        </div>
        <div class="form-group">
            <label for="quantite_stock">quantite stock :</label>
            <input type="number" name="quantite_stock" id="quantite_stock" value="{{old('quantite_stock')}}">
        </div>
        <br>
        <div class="form-group">
            <label for="categorie_id">categorie :</label>
            <select class="form-select" aria-label="Default select example" name="categorie_id">
                <option selected>categorie</option>
                @foreach ($categories as $cat)
                    <option value="{{$cat->id}}">{{$cat->designation}}</option>
                @endforeach
                
            
            </select>
        </div>
          <br>
        <div>
            <input class="but" type="submit" value="Ajouter">
        </div>
    </form>
</div>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
@endsection

resources/views/produits/edit.blade.php
 @extends('layouts.admin')
 @section('title','Modifier un produit')
 @section('content')

<div class="contain">
    <h1 class="edit-h1">Modifier le produit num {{$prod->id}}</h1>
    <form action="{{route('produits.update',["produit"=>$prod->id])}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        @csrf
        <div class="form-group">
        <label for="designation">Designation :</label>
        <input type="text" name="designation" id="designation" value="{{old('designation',$prod->designation)}}">
        </div>
        <br>
        <div class="form-group">
            <label for="prix">prix :</label>
            <input type="number" name="prix" id="prix" value="{{old('prix',$prod->prix_u)}}">
        </div>        
        <br>
        <div class="form-group">
            <label for="quantite_stock">quantite stock :</label>
            <input type="number" name="quantite_stock" id="quantite_stock" value="{{old('quantite_stock',$prod->quantite_stock)}}">
        </div>
        <div class="form-group">
            <label for="image">image :</label>
            <input type="file" name="image" id="image" value="{{old('image',$prod->image)}}">
        </div>
        <br>
        
        <select class="form-select" aria-label="Default select example" name="categorie_id">
            @foreach ($categories as $item)
            @if ($item->id == $prod->categorie->id)
            <option selected value="{{$item->id}}">{{$item->designation}}</option>  
            @else
            <option value="{{$item->id}}">{{$item->designation }}</option>

            @endif
            @endforeach

          </select>
          <br>
          <br>
        <div>
            <input type="submit" value="Modifier">
        </div>
    </form>

    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>
           
           @endforeach
        </ul>
         


        @endif
    </div>
</div>
@endsection

resources/views/produits/index.blade.php
 @extends('layouts.admin')
 @section('title','Gestion des produits')
 @section('content')
     
    <h1>Liste des produits</h1>
    <a class="btn btn-primary mb-3" href="{{route('produits.create')}}">Ajouter un nouveau produit</a>
    <br>
    <div class="searsh">
      <form action="{{route('produits.index')}}" method="GET">
        @csrf
        <label for="designation">designation :</label>
        <input type="text" name="designation" id="designation">
        <label for="min">prix min :</label>
        <input type="number" step="any" name="min" id="min">
        <label for="max">prix max :</label>
        <input type="number" step="any" name="max" id="max">
        <label for="quantite_stock">quantite stock :</label>
        <input type="number" name="quantite_stock" id="quantite_stock">
        <label for="cate">Categeorie</label>
        <select id="cate" name="cate">
        @foreach($categories as $cat)
          <option value="{{$cat->id}}">{{$cat->designation}}</option>
        @endforeach
        <input class="mt-4" type="submit" value="Filter">
 
        </select>
      </form>
    </div>
    <br>
    <table class="table table-stripped" id="tbl">
      <tr>
          <th>Id</th>
        <th>Designation</th>
        <th>prix</th>
        <th>quantite stocke</th>
        <th>categorie</th>
        <th colspan="3">Actions</th>
      </tr>
      @foreach ($produits as $prod)
          <tr>
            <td>{{$prod->id}}</td>
            <td>{{$prod->designation}}</td>
            <td>{{$prod->prix_u}}</td>
            <td>{{$prod->quantite_stock}}</td>
            <td>{{$prod->categorie->designation}}</td>
            <td><a href="{{route('produits.show',["produit"=>$prod->id])}}">Details</a></td>
            <td><a href="{{route('produits.edit',["produit"=>$prod->id])}}">Modifier</a></td>
            <td>
                <form action="{{route('produits.destroy',["produit"=>$prod->id])}}" method="POST">
                    @method('DELETE')
                    @csrf
                    <input type="submit" value="Supprimer" onclick="return confirm('voulez-vous supprimer ce produit?')">
                </form></td>
          </tr>
      @endforeach
    </table>
{{ $produits->links() }}

 @endsection

resources/views/produits/show.blade.php
 @extends('layouts.admin')
 @section('title','Detail d \'une categorie')
 @section('content')
    <a href="{{route('produits.index')}}">Retourner vers la liste des categories</a>
    <h1>Detail de la categorie Num {{$prod->id}}</h1>
    <div>
        <p><strong>Designation:</strong> {{$prod->designation}}</p>
        <p><strong>prix:</strong> {{$prod->prix_u}}</p>
        <p><strong>quantite stock:</strong> {{$prod->quantite_stock}}</p>
        <p><strong>categorie id:</strong> {{$prod->categorie_id}}</p>
    </div>
@endsection